version: 2.0
jobs:
  build:
    docker:
      - image: circleci/python:3.7

      - image: postgres:11.4-alpine
        environment:
          POSTGRES_USER: ci-db-user
          POSTGRES_DB: ci-db
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
      - run:
          name: Running in the python container
          command: |
          python -V
