version: 2.1
orbs:
  heroku: circleci/heroku@0.0.8

docker_images: &docker_images
  docker:
    - image: circleci/python:3.7

    - image: postgres:11.4-alpine
      environment:
        POSTGRES_USER: ci-db-user
        POSTGRES_DB: ci-db

jobs:
  checkout_code:
    <<: *docker_images
    steps:
      - checkout

  deploy_staging:
    <<: *docker_images
    executor: heroku/default

    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: master
          app-name: homekitchen-api-staging
